### ISSUE TITLE
Signature error calling GetReportList

### ISSUE THREAD

**Issue by tresheffron** [beardon/mws-api#93]
I get the following error when calling GetReportList. 

"Error: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."
From previous event:
    at AmazonMwsClient.call (/.../node_modules/mws-api/lib/client.js:130:43)
    at req.query.then (/.../node_modules/mws-api/lib/client.js:254:45)

All the other calls I've tried to the Reports section work fine without error. Suggestions?

**Comment by tresheffron** [comment]
Misunderstood how to call this; misuse of an array parameter. Not an issue.
