### ISSUE TITLE
 Only compatible with Node ^4.0.0. Does it mean 6 and 6+ version isn't supported?

### ISSUE THREAD

**Issue by igauravsehrawat** [beardon/mws-api#95]
By sem versioning, ^4.0.0 tell us that versions 4.x.x are supported and none after that.

Am I right?

Node v4 will be out of LTS soon, can we expect future version of Node to be supported?
I see `unless someone adds a babel precompilation step`, I am interested in doing it, what's the right place to start it?

Thanks

**Comment by tyscorp** [comment]
I'm pretty sure it will work fine on Node >= 4.0.0.

**Comment by igauravsehrawat** [comment]
@tyscorp No, it didn't work for me on node version 7.3.0 and v6.x.x
I get the following error on running any function after providing authenticating tokens.

```
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined,
  _trace: 
   { Error
       at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/somePath/node_modules/bluebird/js/release/debuggability.js:397:19)
       at Promise._then (/somePath/node_modules/bluebird/js/release/promise.js:232:17)
       at Promise.then (/somePath/node_modules/bluebird/js/release/promise.js:125:17)
       at AmazonMwsClient.invoke (/somePath/node_modules/mws-api/lib/client.js:254:28)
       at Object.GetServiceStatus (/somePath/node_modules/mws-api/lib/api.js:39:25)
       at repl:1:26
       at realRunInThisContextScript (vm.js:22:35)
       at sigintHandlersWrap (vm.js:98:12)
       at ContextifyScript.Script.runInThisContext (vm.js:24:12)
       at REPLServer.defaultEval (repl.js:346:29)
       at bound (domain.js:280:14)
       at REPLServer.runBound [as eval] (domain.js:293:12)
       at REPLServer.onLine (repl.js:545:10)
       at emitOne (events.js:101:20)
       at REPLServer.emit (events.js:188:7)
       at REPLServer.Interface._onLine (readline.js:247:10)
       at REPLServer.Interface._line (readline.js:591:8)
       at REPLServer.Interface._ttyWrite (readline.js:870:14)
       at REPLServer.self._ttyWrite (repl.js:618:7)
       at ReadStream.onkeypress (readline.js:126:10)
       at emitTwo (events.js:106:13)
       at ReadStream.emit (events.js:191:7)
       at emitKeys (internal/readline.js:403:14)
       at emitKeys.next (<anonymous>)
       at ReadStream.onData (readline.js:981:36)
       at emitOne (events.js:96:13)
       at ReadStream.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:176:18) _parent: undefined, _promisesCreated: 0, _length: 1 } }
```

Thanks
